# Generated by Django 3.2.18 on 2023-05-17 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password_link_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
