# Generated by Django 3.2.18 on 2023-05-18 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_reset_password_link_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reset_password_link_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
