# Generated by Django 2.2 on 2023-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20230402_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='team\\default.jpg', upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
    ]
