# Generated by Django 3.2.18 on 2023-04-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images/%Y/%m/%d', verbose_name='Blog image'),
        ),
    ]
