# Generated by Django 3.2.18 on 2023-05-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='massage',
            new_name='message',
        ),
    ]
